version: "3"
services:
  app:
    build: .
    tty: true
    user: "${UID}:${GID}"
    command: node /app/split-pdf-bookmarks.js "/input/[INPUT]"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - [SOURCE]:/input/