version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-PDF-Bookmark-Splitor-20250623.080058
    tty: true
    user: "${UID}:${GID}"
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-pdf-bookmark-splitor-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - __SOURCE__:/input/
      - __SOURCE__:/output/